"""Add FileMetadata model for file upload management

Revision ID: 58179317f358
Revises: f8c4a37a9ad1
Create Date: 2025-08-14 02:20:42.879317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58179317f358"
down_revision: Union[str, None] = "f8c4a37a9ad1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
