"""add_dashboard_and_collaboration_models_for_real_time_features

Revision ID: 4b8a12e5c456
Revises: fbfc70d0db81
Create Date: 2025-08-14 04:15:45.436661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b8a12e5c456"
down_revision: Union[str, None] = "fbfc70d0db81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
