"""Add Summary and SummaryVersion models for AI summarization

Revision ID: 5073c26f5bc7
Revises: 58179317f358
Create Date: 2025-08-14 02:44:45.322906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5073c26f5bc7"
down_revision: Union[str, None] = "58179317f358"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
