"""Add usage tracking and quota management models

Revision ID: 19a16abcb7b1
Revises: 5073c26f5bc7
Create Date: 2025-08-14 03:11:32.933744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19a16abcb7b1"
down_revision: Union[str, None] = "5073c26f5bc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
