"""Add comprehensive quiz system models and relationships

Revision ID: 7793d930f6d3
Revises: ac050dca5a17
Create Date: 2025-08-14 03:36:37.873909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7793d930f6d3"
down_revision: Union[str, None] = "ac050dca5a17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_metadata",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename"),
    )
    op.create_index(op.f("ix_file_metadata_id"), "file_metadata", ["id"], unique=False)
    op.create_index(
        op.f("ix_file_metadata_user_id"), "file_metadata", ["user_id"], unique=False
    )
    op.create_table(
        "usage_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=36), nullable=True),
        sa.Column("ai_provider", sa.String(length=50), nullable=False),
        sa.Column("ai_model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("request_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ai_provider_model",
        "usage_records",
        ["ai_provider", "ai_model"],
        unique=False,
    )
    op.create_index(
        "idx_correlation_id", "usage_records", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_operation_type", "usage_records", ["operation_type"], unique=False
    )
    op.create_index("idx_status", "usage_records", ["status"], unique=False)
    op.create_index(
        "idx_user_created_at", "usage_records", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "user_quotas",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quota_month", sa.Date(), nullable=False),
        sa.Column("token_limit", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_limit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("cost_used", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("summary_limit", sa.Integer(), nullable=False),
        sa.Column("summaries_used", sa.Integer(), nullable=False),
        sa.Column("quiz_limit", sa.Integer(), nullable=False),
        sa.Column("quizzes_used", sa.Integer(), nullable=False),
        sa.Column("is_premium", sa.Boolean(), nullable=False),
        sa.Column("premium_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "quota_month", name="unique_user_quota_month"),
    )
    op.create_index(
        "idx_user_quota_month", "user_quotas", ["user_id", "quota_month"], unique=False
    )
    op.create_table(
        "quizzes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=20), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("estimated_time_minutes", sa.Integer(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("topics_covered", sa.JSON(), nullable=True),
        sa.Column("learning_objectives", sa.JSON(), nullable=True),
        sa.Column(
            "content_complexity_score", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column("ai_provider", sa.String(length=50), nullable=False),
        sa.Column("ai_model_used", sa.String(length=100), nullable=False),
        sa.Column("prompt_template", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("generation_cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "ai_confidence_score", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column(
            "question_quality_avg", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("shuffle_questions", sa.Boolean(), nullable=False),
        sa.Column("shuffle_answers", sa.Boolean(), nullable=False),
        sa.Column("show_correct_answers", sa.Boolean(), nullable=False),
        sa.Column("allow_retries", sa.Boolean(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column("passing_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("completed_attempts", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("average_completion_time", sa.Integer(), nullable=True),
        sa.Column("difficulty_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("custom_instructions", sa.Text(), nullable=True),
        sa.Column("focus_areas", sa.JSON(), nullable=True),
        sa.Column("excluded_topics", sa.JSON(), nullable=True),
        sa.Column("question_types", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "estimated_time_minutes > 0", name="positive_estimated_time"
        ),
        sa.CheckConstraint(
            "progress_percentage >= 0 AND progress_percentage <= 100",
            name="valid_progress",
        ),
        sa.CheckConstraint(
            "quality_score IS NULL OR (quality_score >= 0.0 AND quality_score <= 5.0)",
            name="valid_quality_score",
        ),
        sa.CheckConstraint("question_count > 0", name="positive_question_count"),
        sa.CheckConstraint(
            "user_rating IS NULL OR (user_rating >= 1 AND user_rating <= 5)",
            name="valid_user_rating",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_metadata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_quiz_created_at", "quizzes", ["created_at"], unique=False)
    op.create_index(
        "idx_quiz_file_status", "quizzes", ["file_id", "status"], unique=False
    )
    op.create_index(
        "idx_quiz_user_status", "quizzes", ["user_id", "status"], unique=False
    )
    op.create_table(
        "quota_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quota_id", sa.String(length=36), nullable=False),
        sa.Column("change_type", sa.String(length=50), nullable=False),
        sa.Column("field_changed", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.String(length=100), nullable=True),
        sa.Column("new_value", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quota_id"],
            ["user_quotas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "summaries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary_type", sa.String(length=50), nullable=False),
        sa.Column("ai_provider", sa.String(length=50), nullable=False),
        sa.Column("ai_model_used", sa.String(length=100), nullable=False),
        sa.Column("prompt_template", sa.String(length=100), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("generation_cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("original_word_count", sa.Integer(), nullable=True),
        sa.Column("summary_word_count", sa.Integer(), nullable=True),
        sa.Column("compression_ratio", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("readability_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("custom_instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_metadata.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quiz_id", sa.String(length=36), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("difficulty_level", sa.String(length=20), nullable=False),
        sa.Column("points", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("topic", sa.String(length=100), nullable=True),
        sa.Column("learning_objective", sa.String(length=200), nullable=True),
        sa.Column("cognitive_level", sa.String(length=50), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("source_reference", sa.String(length=200), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "ai_confidence_score", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column("difficulty_rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("clarity_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("times_answered", sa.Integer(), nullable=False),
        sa.Column("times_correct", sa.Integer(), nullable=False),
        sa.Column("average_response_time", sa.Integer(), nullable=True),
        sa.Column(
            "discrimination_index", sa.Numeric(precision=4, scale=3), nullable=True
        ),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("allow_partial_credit", sa.Boolean(), nullable=False),
        sa.Column("case_sensitive", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("order_index >= 0", name="non_negative_order"),
        sa.CheckConstraint("points > 0", name="positive_points"),
        sa.CheckConstraint(
            "times_correct <= times_answered", name="logical_answer_counts"
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_question_quiz_order", "questions", ["quiz_id", "order_index"], unique=False
    )
    op.create_index(
        "idx_question_type_difficulty",
        "questions",
        ["question_type", "difficulty_level"],
        unique=False,
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("quiz_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "max_possible_score", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("percentage_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
        sa.Column("time_limit_seconds", sa.Integer(), nullable=True),
        sa.Column("questions_answered", sa.Integer(), nullable=False),
        sa.Column("questions_correct", sa.Integer(), nullable=False),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("learning_path", sa.JSON(), nullable=True),
        sa.Column("difficulty_progression", sa.JSON(), nullable=True),
        sa.Column("topic_scores", sa.JSON(), nullable=True),
        sa.Column("response_patterns", sa.JSON(), nullable=True),
        sa.Column("user_feedback", sa.Text(), nullable=True),
        sa.Column("difficulty_rating", sa.Integer(), nullable=True),
        sa.Column("instructor_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_number > 0", name="positive_attempt_number"),
        sa.CheckConstraint(
            "difficulty_rating IS NULL OR (difficulty_rating >= 1 AND difficulty_rating <= 5)",
            name="valid_difficulty_rating",
        ),
        sa.CheckConstraint(
            "questions_correct <= questions_answered", name="logical_correct_count"
        ),
        sa.CheckConstraint("total_score >= 0", name="non_negative_score"),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_attempt_quiz_user", "quiz_attempts", ["quiz_id", "user_id"], unique=False
    )
    op.create_index(
        "idx_attempt_status_started",
        "quiz_attempts",
        ["status", "started_at"],
        unique=False,
    )
    op.create_table(
        "summary_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("summary_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("ai_provider", sa.String(length=50), nullable=False),
        sa.Column("ai_model_used", sa.String(length=100), nullable=False),
        sa.Column("prompt_template", sa.String(length=100), nullable=True),
        sa.Column("custom_instructions", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("generation_cost", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("user_rating", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["summaries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("distractor_type", sa.String(length=50), nullable=True),
        sa.Column("times_selected", sa.Integer(), nullable=False),
        sa.Column(
            "selection_percentage", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("order_index >= 0", name="non_negative_order"),
        sa.CheckConstraint("times_selected >= 0", name="non_negative_selections"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_answer_correct", "answers", ["question_id", "is_correct"], unique=False
    )
    op.create_index(
        "idx_answer_question_order",
        "answers",
        ["question_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "question_responses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("user_answer", sa.Text(), nullable=True),
        sa.Column("selected_answer_ids", sa.JSON(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("points_earned", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("max_points", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("response_time_seconds", sa.Integer(), nullable=False),
        sa.Column("time_to_first_interaction", sa.Integer(), nullable=True),
        sa.Column("interaction_count", sa.Integer(), nullable=False),
        sa.Column("confidence_level", sa.Integer(), nullable=True),
        sa.Column("difficulty_perception", sa.Integer(), nullable=True),
        sa.Column(
            "answered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence_level IS NULL OR (confidence_level >= 1 AND confidence_level <= 5)",
            name="valid_confidence",
        ),
        sa.CheckConstraint(
            "difficulty_perception IS NULL OR (difficulty_perception >= 1 AND difficulty_perception <= 5)",
            name="valid_difficulty_perception",
        ),
        sa.CheckConstraint("interaction_count >= 0", name="non_negative_interactions"),
        sa.CheckConstraint("points_earned <= max_points", name="earned_not_exceed_max"),
        sa.CheckConstraint(
            "response_time_seconds >= 0", name="non_negative_response_time"
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["quiz_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_response_attempt_question",
        "question_responses",
        ["attempt_id", "question_id"],
        unique=False,
    )
    op.create_index(
        "idx_response_correct_time",
        "question_responses",
        ["is_correct", "response_time_seconds"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_response_correct_time", table_name="question_responses")
    op.drop_index("idx_response_attempt_question", table_name="question_responses")
    op.drop_table("question_responses")
    op.drop_index("idx_answer_question_order", table_name="answers")
    op.drop_index("idx_answer_correct", table_name="answers")
    op.drop_table("answers")
    op.drop_table("summary_versions")
    op.drop_index("idx_attempt_status_started", table_name="quiz_attempts")
    op.drop_index("idx_attempt_quiz_user", table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    op.drop_index("idx_question_type_difficulty", table_name="questions")
    op.drop_index("idx_question_quiz_order", table_name="questions")
    op.drop_table("questions")
    op.drop_table("summaries")
    op.drop_table("quota_history")
    op.drop_index("idx_quiz_user_status", table_name="quizzes")
    op.drop_index("idx_quiz_file_status", table_name="quizzes")
    op.drop_index("idx_quiz_created_at", table_name="quizzes")
    op.drop_table("quizzes")
    op.drop_index("idx_user_quota_month", table_name="user_quotas")
    op.drop_table("user_quotas")
    op.drop_index("idx_user_created_at", table_name="usage_records")
    op.drop_index("idx_status", table_name="usage_records")
    op.drop_index("idx_operation_type", table_name="usage_records")
    op.drop_index("idx_correlation_id", table_name="usage_records")
    op.drop_index("idx_ai_provider_model", table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_file_metadata_user_id"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_id"), table_name="file_metadata")
    op.drop_table("file_metadata")
    # ### end Alembic commands ###
