"""add_notification_system_tables_and_relationships

Revision ID: fbfc70d0db81
Revises: d32c90264896
Create Date: 2025-08-14 04:07:36.483609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbfc70d0db81"
down_revision: Union[str, None] = "d32c90264896"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
