"""add_notification_system_models_for_comprehensive_real_time_communication

Revision ID: d32c90264896
Revises: 7793d930f6d3
Create Date: 2025-08-14 03:52:10.395569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d32c90264896"
down_revision: Union[str, None] = "7793d930f6d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
