"""add community_code to community

Revision ID: b73f03593bdb
Revises: e00c764779ff
Create Date: 2025-05-30 03:43:21.944420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b73f03593bdb'
down_revision: Union[str, None] = 'e00c764779ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('community_code', sa.String(length=10), nullable=False))
    op.create_index(op.f('ix_community_community_code'), 'community', ['community_code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_community_code'), table_name='community')
    op.drop_column('community', 'community_code')
    # ### end Alembic commands ###
