"""Add UserFreeApiUsage model

Revision ID: dafbc7590770
Revises: 8df9d10bb74e
Create Date: 2025-05-29 22:37:07.420482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafbc7590770'
down_revision: Union[str, None] = '8df9d10bb74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove or comment out the enum creation since it already exists
    # op.create_enum('ai_provider_enum', [('OpenAI', ), ('Google', ), ('Other', )])
    
    op.create_table('user_free_api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_provider', sa.Enum('OpenAI', 'Google', 'Other', name='ai_provider_enum'), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_free_api_usage_id'), 'user_free_api_usage', ['id'], unique=False)
    op.drop_index('idx_gemini_file_cache_api_key_id', table_name='gemini_file_cache')
    op.drop_index('idx_gemini_file_cache_physical_file_id', table_name='gemini_file_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gemini_file_cache_physical_file_id', 'gemini_file_cache', ['physical_file_id'], unique=False)
    op.create_index('idx_gemini_file_cache_api_key_id', 'gemini_file_cache', ['api_key_id'], unique=False)
    op.drop_index(op.f('ix_user_free_api_usage_id'), table_name='user_free_api_usage')
    op.drop_table('user_free_api_usage')
    # Don't drop the enum since other tables might be using it
    # op.drop_enum('ai_provider_enum')
    # ### end Alembic commands ###
